#include "hrs_scene_manager.h"

#include <Math/float4.h>

void HorusSceneManager::Init()
{
	m_CreationModesMap_ = {
		{"GPU0", RPR_CREATION_FLAGS_ENABLE_GPU0},
		{"GPU1", RPR_CREATION_FLAGS_ENABLE_GPU1},
		{"GPU2", RPR_CREATION_FLAGS_ENABLE_GPU2},
		{"GPU3", RPR_CREATION_FLAGS_ENABLE_GPU3},
		{"GPU4", RPR_CREATION_FLAGS_ENABLE_GPU4},
		{"GPU5", RPR_CREATION_FLAGS_ENABLE_GPU5},
		{"GPU6", RPR_CREATION_FLAGS_ENABLE_GPU6},
		{"GPU7", RPR_CREATION_FLAGS_ENABLE_GPU7},
		{"GPU8", RPR_CREATION_FLAGS_ENABLE_GPU8},
		{"GPU9", RPR_CREATION_FLAGS_ENABLE_GPU9},
		{"GPU10", RPR_CREATION_FLAGS_ENABLE_GPU10},
		{"GPU11", RPR_CREATION_FLAGS_ENABLE_GPU11}
	};

	m_RenderModeMap_ = {

		{ "GI", RPR_RENDER_MODE_GLOBAL_ILLUMINATION},
		{ "DI", RPR_RENDER_MODE_DIRECT_ILLUMINATION}  ,
		{ "DI_FLAT", RPR_RENDER_MODE_DIRECT_ILLUMINATION_NO_SHADOW},
		{ "WIRE", RPR_RENDER_MODE_WIREFRAME},
		{ "MI", RPR_RENDER_MODE_MATERIAL_INDEX},
		{ "POS", RPR_RENDER_MODE_POSITION},
		{ "NORMAL", RPR_RENDER_MODE_NORMAL},
		{ "TEX", RPR_RENDER_MODE_TEXCOORD},
		{ "AO", RPR_RENDER_MODE_AMBIENT_OCCLUSION},
		{ "DIFF", RPR_RENDER_MODE_DIFFUSE}
	};

	m_CameraModeMap_ = {
		{"PERSPECTIVE", RPR_CAMERA_MODE_PERSPECTIVE},
		{"ORTHO", RPR_CAMERA_MODE_ORTHOGRAPHIC},
		{"LONGLAT360", RPR_CAMERA_MODE_LATITUDE_LONGITUDE_360},
		{"LONLATSTEREO", RPR_CAMERA_MODE_LATITUDE_LONGITUDE_STEREO},
		{"CUBEMAP", RPR_CAMERA_MODE_CUBEMAP},
		{"CUBEMAPSTEREO", RPR_CAMERA_MODE_CUBEMAP_STEREO},
		{"FISHEYE", RPR_CAMERA_MODE_FISHEYE}
	};




}
